name: Tests within Conda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: parq
        environment-file: setup/parq.yml
        python-version: 3.11
    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check || {
          echo "Ruff check failed. Please run 'ruff format .' before trying again."
          exit 1
        }
    - name: Test with unittest
      run: |
        python -m unittest discover test
